name: MMS Composer CI Master branch pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  master-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.SECRET_GCP_SERVICE_ACCOUNT }}
        export_default_credentials: true
    
    - name: Deploy files to Composer
      env:
        COMPOSER_BUCKET: 'composer-bucket-name'
      run: |
        gsutil cp dags/* gs://$COMPOSER_BUCKET/dags/
